export enum BrowserPermission {
    Geolocation = 'geolocation',
    Camera = 'camera',
    Microphone = 'microphone',
    Notifications = 'notifications',
    Midi = 'midi',
    Push = 'push',
    ClipboardRead = 'clipboard-read',
    ClipboardWrite = 'clipboard-write',
    PaymentHandler = 'payment-handler',
    Usb = 'usb',
    Bluetooth = 'bluetooth',
    Accelerometer = 'accelerometer',
    Gyroscope = 'gyroscope',
    Magnetometer = 'magnetometer',
    AmbientLightSensor = 'ambient-light-sensor',
    BackgroundSync = 'background-sync',
    PersistentStorage = 'persistent-storage',
    ScreenWakeLock = 'screen-wake-lock',
    WebShare = 'web-share',
    XrSpatialTracking = 'xr-spatial-tracking',
}